# Generated by Django 4.2.5 on 2023-09-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='worker_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
