# Generated by Django 4.2.5 on 2023-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_requests_worker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('work_data', models.JSONField()),
                ('worker_name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.IntegerField(default=0)),
                ('send_to_collect', models.BooleanField(default=False)),
                ('collect_date', models.DateField(blank=True)),
                ('paid_by_company', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='To_Pay_Or_Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('work_data', models.JSONField()),
                ('worker_name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.IntegerField(default=0)),
                ('paid_by_company', models.BooleanField(default=False)),
                ('work_data_to_pay', models.JSONField()),
                ('total_amount_to_pay', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('pay_date', models.DateField(blank=True)),
                ('amount_earned', models.IntegerField(default=0)),
            ],
        ),
    ]
