# Generated by Django 4.2.5 on 2023-09-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_to_collect_paid_by_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_collect',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='to_pay_or_paid',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
